/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TarsCounter {
        "initialValue": number;
    }
}
declare global {
    interface HTMLTarsCounterElement extends Components.TarsCounter, HTMLStencilElement {
    }
    var HTMLTarsCounterElement: {
        prototype: HTMLTarsCounterElement;
        new (): HTMLTarsCounterElement;
    };
    interface HTMLElementTagNameMap {
        "tars-counter": HTMLTarsCounterElement;
    }
}
declare namespace LocalJSX {
    interface TarsCounter {
        "initialValue"?: number;
    }
    interface IntrinsicElements {
        "tars-counter": TarsCounter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tars-counter": LocalJSX.TarsCounter & JSXBase.HTMLAttributes<HTMLTarsCounterElement>;
        }
    }
}
