/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TarsCounter {
        "initialValue": number;
    }
    interface TarsInput {
    }
    interface TarsInputPassword {
        "getValue": () => Promise<boolean>;
        "inputName": string;
        /**
          * Set placeholder.
         */
        "inputPlaceholder"?: string;
        "isPasswordVisible": boolean;
        "value"?: string;
    }
}
declare global {
    interface HTMLTarsCounterElement extends Components.TarsCounter, HTMLStencilElement {
    }
    var HTMLTarsCounterElement: {
        prototype: HTMLTarsCounterElement;
        new (): HTMLTarsCounterElement;
    };
    interface HTMLTarsInputElement extends Components.TarsInput, HTMLStencilElement {
    }
    var HTMLTarsInputElement: {
        prototype: HTMLTarsInputElement;
        new (): HTMLTarsInputElement;
    };
    interface HTMLTarsInputPasswordElement extends Components.TarsInputPassword, HTMLStencilElement {
    }
    var HTMLTarsInputPasswordElement: {
        prototype: HTMLTarsInputPasswordElement;
        new (): HTMLTarsInputPasswordElement;
    };
    interface HTMLElementTagNameMap {
        "tars-counter": HTMLTarsCounterElement;
        "tars-input": HTMLTarsInputElement;
        "tars-input-password": HTMLTarsInputPasswordElement;
    }
}
declare namespace LocalJSX {
    interface TarsCounter {
        "initialValue"?: number;
    }
    interface TarsInput {
    }
    interface TarsInputPassword {
        "inputName"?: string;
        /**
          * Set placeholder.
         */
        "inputPlaceholder"?: string;
        "isPasswordVisible"?: boolean;
        "onShowPassword"?: (event: CustomEvent<boolean>) => void;
        "value"?: string;
    }
    interface IntrinsicElements {
        "tars-counter": TarsCounter;
        "tars-input": TarsInput;
        "tars-input-password": TarsInputPassword;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tars-counter": LocalJSX.TarsCounter & JSXBase.HTMLAttributes<HTMLTarsCounterElement>;
            "tars-input": LocalJSX.TarsInput & JSXBase.HTMLAttributes<HTMLTarsInputElement>;
            "tars-input-password": LocalJSX.TarsInputPassword & JSXBase.HTMLAttributes<HTMLTarsInputPasswordElement>;
        }
    }
}
